name: Build PassPing Extension
on:
    workflow_dispatch: 
    push:
        branches: ["main"]
        paths-ignore:
            - '*.png'
            - '*.jpg'
            - 'README.md'
            - '../README.md'
            - '.github/workflows/ci-cd-pipeline.yml'
            - 'passping-extension/build/manifest.json'
            - 'passping-extension/build/*'
    pull_request:
        branches: ["main"]
jobs:
  build-extension:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./passping-extension

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22
            cache-dependency-path: ./passping-extension/package-lock.json
            cache: 'npm'

      # npm CLEAN install: For automation and ensuring reproducible builds. 
      # Dependencies installed as per dependency tree in package-lock.json.
      - name: Install required dependencies
        run: npm ci
         
      - name: Build ZIP file for extension 
        run: npm run build:zip --if-present

      - name: Create ZIP file
        run: |
            cd build 
            zip -r ../passping-ext-build.zip ./*
    
      - name:  Upload ZIP file as artifact 
        uses: actions/upload-artifact@v4
        with:
            name: passping-extension-build
            path: passping-extension/passping-ext-build.zip
            retention-days: 1

  # New job - Deploy the newly-built PassPing to the Chrome web store   
  deploy-extension:
    runs-on: ubuntu-latest
    needs: build-extension

    steps:
      - name: Find downloaded ZIP
        run: |
            pwd
            ls -la
            find .. -name "*.zip"
      
      - name: Download PassPing artifact
        uses:  actions/download-artifact@v4
        with:
            name: passping-extension-build
    
      - name: Verify PassPing artifact existence 
        run: |
            if [ ! -f passping-ext-build.zip ]; then
                echo "Error: PassPing artifact not found."
                exit 1
            fi

            echo "PassPing artifact existence verified. Proceeding to deployment."

      - name:  Google Chrome Web Store Upload
        run: npx chrome-webstore-upload-cli upload --source passping-ext-build.zip --extension-id "${{ secrets.PASSPING_ID }}"
        env:
            CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
            PUBLISHER_ID: ${{ secrets.GOOGLE_PUBLISHER_ID }}



            
